/****************************************************
 * COPYRIGHT (C)  KISEL STUDIOS. All rights reserved.
 *
 * FILE:          COMMON_COLORS.H. 
 * PURPOSE:       Define of Basic Colors.
 * PROGRAMMER:    Ivan Pashkov, 10-5, IP5.
 * LAST UPDATE:   13.01.2024
 *
 * PROJECT:       Paint Win32 Application
 *
 * NOTIFICATION:  No part of this file can be
 *                changed without agrements
 *                I.Pashkov and Kisel Studios.
 ****************************************************/



#if (defined _MSC_VER) && (_MSC_VER >= 400) 
#pragma once
#endif /* _WIN32 */

#ifndef __COMMON_COLORS_H_
#define __COMMON_COLORS_H_



/* BLACK */
#ifndef GFX_BLACK
#define GFX_BLACK       0x000000
#endif /* !GFX_WHITE */


/* WHITE */
#ifndef GFX_WHITE
#define GFX_WHITE       0xFFFFFF
#endif /* !GFX_WHITE */


/* RED */
#ifndef GFX_RED
#define GFX_RED         0xFF0000
#endif /* !GFX_WHITE */


/* LIME */
#ifndef GFX_LIME
#define GFX_LIME        0xC8FF00
#endif /* !GFX_LIME */


/* LIGHT_BLUE */
#ifndef GFX_LIGHT_BLUE
#define GFX_LIGHT_BLUE  0x00C7FF
#endif /* !GFX_LIGHT_BLUE */


/* YELLOW */
#ifndef GFX_YELLOW
#define GFX_YELLOW      0xC2B20B
#endif /* !GFX_YELLOW */



#endif /* !__COMMON_COLORS_H_ */



/* END OF 'COMMON_COLORS.H' FILE */

